name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 8 & cache Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Build & run tests
        run: ./gradlew clean build --no-daemon
