name: Create Publish PR

on:
  push:
    branches: [ main ]
  workflow_dispatch: # trigger manually

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Increment version
        id: version
        run: |
          CURRENT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          NEW_VERSION="${CURRENT_VERSION%.*}.$((${CURRENT_VERSION##*.} + 1))"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update build.gradle.kts version
        run: |
          sed -i "s/version = \"$CURRENT_VERSION\"/version = \"${{ steps.version.outputs.NEW_VERSION }}\"/g" build.gradle.kts

      - name: Update README version
        run: |
          sed -i "s/<version>$CURRENT_VERSION<\/version>/<version>${{ steps.version.outputs.NEW_VERSION }}<\/version>/g" README.md
          sed -i "s/implementation(\"com.cjcrafter:foliascheduler:$CURRENT_VERSION\")/implementation(\"com.cjcrafter:foliascheduler:${{ steps.version.outputs.NEW_VERSION }}\")/g" README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version to ${{ steps.version.outputs.NEW_VERSION }}
          title: "Publish: Release ${{ steps.version.outputs.NEW_VERSION }}"
          body: |
            This PR is ready for publishing:
            - Version bumped to ${{ steps.version.outputs.NEW_VERSION }}
            - README updated
            
            Please review and approve to publish this version.
          branch: release-${{ steps.version.outputs.NEW_VERSION }}
          base: master
          labels: publish
